name: Build catalyst container
on:
  push:
    paths:
      - 'Dockerfile'
jobs:
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/whatamisupposedtoputhere/fex-rootfs-catalyst:latest
      - name: Clean
        uses: quartx-analytics/ghcr-cleaner@v1
        with:
          owner-type: user
          token: ${{ secrets.PAT_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          delete-untagged: true
          repository-name: ${{ github.repository }}
